name: Create Release
on:
  push:
    tags: [v*]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate release .zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'media-center.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "media-center.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
